// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoAnonymizer.Database;

#nullable disable

namespace VideoAnonymizer.Database.Migrations
{
    [DbContext(typeof(VideoAnonymizerDbContext))]
    [Migration("20260321133604_anonomizedPathNullable")]
    partial class anonomizedPathNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("AnalyzedFrames");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.DetectedObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalyzedFrameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.Property<string>("TrackId")
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedFrameId");

                    b.ToTable("DetectedObjects");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonomizedPath")
                        .HasColumnType("text");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.HasOne("VideoAnonymizer.Database.Video", "Video")
                        .WithMany("AnalyzedFrames")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.DetectedObject", b =>
                {
                    b.HasOne("VideoAnonymizer.Database.AnalyzedFrame", "AnalyzedFrame")
                        .WithMany("DetectedObjects")
                        .HasForeignKey("AnalyzedFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalyzedFrame");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.Navigation("DetectedObjects");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.Video", b =>
                {
                    b.Navigation("AnalyzedFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
