// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace VideoAnonymizer.ApiService.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Predicting object positions between analyzed frames")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("object_interpolation")]
    public partial class PredictingObjectPositionsBetweenAnalyzedFramesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "object_interpolation"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Predicting object positions between analyzed frames", "  As a reviewer anonymizing a video with sampled detections\r\n  I want tracked obj" +
                "ects to be predicted between analyzed frames\r\n  So that moving license plates an" +
                "d faces stay covered while the export renders every frame.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "RelevantDetectedObjectInterpolation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/RelevantDetectedObjectInterpolation.feature.ndjson", 26);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A tracked object\'s box is interpolated halfway between analyzed frames")]
        public async global::System.Threading.Tasks.Task ATrackedObjectsBoxIsInterpolatedHalfwayBetweenAnalyzedFrames()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tracked object\'s box is interpolated halfway between analyzed frames", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "y",
                            "width",
                            "height",
                            "blurShape"});
                table13.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "20",
                            "30",
                            "40",
                            "rectangle"});
                table13.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "60",
                            "50",
                            "20",
                            "rectangle"});
#line 8
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table13, "Given ");
#line hidden
#line 12
    await testRunner.WhenAsync("the processor predicts objects at 0.5 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x",
                            "y",
                            "width",
                            "height",
                            "blurShape"});
                table14.AddRow(new string[] {
                            "7",
                            "55",
                            "40",
                            "40",
                            "30",
                            "rectangle"});
#line 13
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An analyzed frame keeps its exact detected box")]
        public async global::System.Threading.Tasks.Task AnAnalyzedFrameKeepsItsExactDetectedBox()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An analyzed frame keeps its exact detected box", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table15.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table15.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 18
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table15, "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("the processor predicts objects at 1.0 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table16.AddRow(new string[] {
                            "7",
                            "100"});
#line 23
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Interpolation can be disabled while buffer coverage still applies")]
        public async global::System.Threading.Tasks.Task InterpolationCanBeDisabledWhileBufferCoverageStillApplies()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interpolation can be disabled while buffer coverage still applies", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table17.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table17.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 28
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table17, "Given ");
#line hidden
#line 32
    await testRunner.AndAsync("object interpolation is disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("the processor predicts objects at 0.5 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table18.AddRow(new string[] {
                            "7",
                            "10"});
#line 34
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A track without a next sample stays visible during its own post-buffer")]
        public async global::System.Threading.Tasks.Task ATrackWithoutANextSampleStaysVisibleDuringItsOwnPost_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A track without a next sample stays visible during its own post-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table19.AddRow(new string[] {
                            "0.0",
                            "1",
                            "10"});
                table19.AddRow(new string[] {
                            "1.0",
                            "2",
                            "100"});
#line 39
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table19, "Given ");
#line hidden
#line 43
    await testRunner.WhenAsync("the processor predicts objects at 0.15 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("the predicted tracks are 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A track without a next sample expires after its own post-buffer")]
        public async global::System.Threading.Tasks.Task ATrackWithoutANextSampleExpiresAfterItsOwnPost_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A track without a next sample expires after its own post-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table20.AddRow(new string[] {
                            "0.0",
                            "1",
                            "10"});
                table20.AddRow(new string[] {
                            "1.0",
                            "2",
                            "100"});
#line 47
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table20, "Given ");
#line hidden
#line 51
    await testRunner.WhenAsync("the processor predicts objects at 1.15 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("the predicted tracks are 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An upcoming track is used shortly before its first analyzed sample")]
        public async global::System.Threading.Tasks.Task AnUpcomingTrackIsUsedShortlyBeforeItsFirstAnalyzedSample()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An upcoming track is used shortly before its first analyzed sample", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "blurShape"});
                table21.AddRow(new string[] {
                            "1.0",
                            "1",
                            "100",
                            "rectangle"});
#line 55
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table21, "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync("the processor predicts objects at 0.85 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x",
                            "blurShape"});
                table22.AddRow(new string[] {
                            "1",
                            "100",
                            "rectangle"});
#line 59
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table22, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A tracked object keeps moving before its first analyzed sample during the buffer")]
        public async global::System.Threading.Tasks.Task ATrackedObjectKeepsMovingBeforeItsFirstAnalyzedSampleDuringTheBuffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tracked object keeps moving before its first analyzed sample during the buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table23.AddRow(new string[] {
                            "1.0",
                            "1",
                            "100"});
                table23.AddRow(new string[] {
                            "2.0",
                            "1",
                            "190"});
#line 64
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table23, "Given ");
#line hidden
#line 68
    await testRunner.WhenAsync("the processor predicts objects at 0.8 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table24.AddRow(new string[] {
                            "1",
                            "82"});
#line 69
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table24, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A tracked object keeps moving after its last analyzed sample during the buffer")]
        public async global::System.Threading.Tasks.Task ATrackedObjectKeepsMovingAfterItsLastAnalyzedSampleDuringTheBuffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tracked object keeps moving after its last analyzed sample during the buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table25.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table25.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 74
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table25, "Given ");
#line hidden
#line 78
    await testRunner.WhenAsync("the processor predicts objects at 1.2 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table26.AddRow(new string[] {
                            "7",
                            "118"});
#line 79
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table26, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A tracked object is not visible after its post-buffer elapses")]
        public async global::System.Threading.Tasks.Task ATrackedObjectIsNotVisibleAfterItsPost_BufferElapses()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tracked object is not visible after its post-buffer elapses", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table27.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table27.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 84
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table27, "Given ");
#line hidden
#line 88
    await testRunner.WhenAsync("the processor predicts objects at 1.4 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A tracked object can move partly outside the frame during extrapolation")]
        public async global::System.Threading.Tasks.Task ATrackedObjectCanMovePartlyOutsideTheFrameDuringExtrapolation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A tracked object can move partly outside the frame during extrapolation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 91
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table28.AddRow(new string[] {
                            "0.0",
                            "7",
                            "20"});
                table28.AddRow(new string[] {
                            "1.0",
                            "7",
                            "-10"});
#line 92
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table28, "Given ");
#line hidden
#line 96
    await testRunner.WhenAsync("the processor predicts objects at 1.2 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x",
                            "width"});
                table29.AddRow(new string[] {
                            "7",
                            "-16",
                            "30"});
#line 97
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table29, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An upcoming track is not used outside the time buffer")]
        public async global::System.Threading.Tasks.Task AnUpcomingTrackIsNotUsedOutsideTheTimeBuffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An upcoming track is not used outside the time buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 101
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table30.AddRow(new string[] {
                            "1.0",
                            "1",
                            "100"});
#line 102
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table30, "Given ");
#line hidden
#line 105
    await testRunner.WhenAsync("the processor predicts objects at 0.70 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An upcoming track is not used when the time buffer is disabled")]
        public async global::System.Threading.Tasks.Task AnUpcomingTrackIsNotUsedWhenTheTimeBufferIsDisabled()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An upcoming track is not used when the time buffer is disabled", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table31.AddRow(new string[] {
                            "1.0",
                            "1",
                            "100"});
#line 109
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table31, "Given ");
#line hidden
#line 112
    await testRunner.WhenAsync("the processor predicts objects at 0.85 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Untracked detections are separate one-object segments")]
        public async global::System.Threading.Tasks.Task UntrackedDetectionsAreSeparateOne_ObjectSegments()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Untracked detections are separate one-object segments", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table32.AddRow(new string[] {
                            "0.0",
                            "",
                            "10"});
                table32.AddRow(new string[] {
                            "1.0",
                            "",
                            "100"});
#line 116
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table32, "Given ");
#line hidden
#line 120
    await testRunner.WhenAsync("the processor predicts objects at 0.5 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An untracked occurrence uses the inherited global pre-buffer")]
        public async global::System.Threading.Tasks.Task AnUntrackedOccurrenceUsesTheInheritedGlobalPre_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An untracked occurrence uses the inherited global pre-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 123
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table33.AddRow(new string[] {
                            "1.0",
                            "",
                            "100"});
#line 124
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table33, "Given ");
#line hidden
#line 127
    await testRunner.WhenAsync("the processor predicts objects at 0.85 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table34.AddRow(new string[] {
                            "",
                            "100"});
#line 128
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table34, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("An untracked occurrence uses the inherited global post-buffer")]
        public async global::System.Threading.Tasks.Task AnUntrackedOccurrenceUsesTheInheritedGlobalPost_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An untracked occurrence uses the inherited global post-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 132
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table35.AddRow(new string[] {
                            "1.0",
                            "",
                            "100"});
#line 133
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table35, "Given ");
#line hidden
#line 136
    await testRunner.WhenAsync("the processor predicts objects at 1.15 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x"});
                table36.AddRow(new string[] {
                            "",
                            "100"});
#line 137
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table36, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A consecutive segment inherits the global pre-buffer before its first occurrence")]
        public async global::System.Threading.Tasks.Task AConsecutiveSegmentInheritsTheGlobalPre_BufferBeforeItsFirstOccurrence()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A consecutive segment inherits the global pre-buffer before its first occurrence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 141
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table37.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table37.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 142
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table37, "Given ");
#line hidden
#line 146
    await testRunner.WhenAsync("the processor predicts objects at -0.15 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
    await testRunner.ThenAsync("the predicted tracks are 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A consecutive segment inherits the global post-buffer after its last occurrence")]
        public async global::System.Threading.Tasks.Task AConsecutiveSegmentInheritsTheGlobalPost_BufferAfterItsLastOccurrence()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A consecutive segment inherits the global post-buffer after its last occurrence", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 149
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x"});
                table38.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10"});
                table38.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100"});
#line 150
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table38, "Given ");
#line hidden
#line 154
    await testRunner.WhenAsync("the processor predicts objects at 1.15 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 155
    await testRunner.ThenAsync("the predicted tracks are 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A first-occurrence pre override replaces the global pre-buffer")]
        public async global::System.Threading.Tasks.Task AFirst_OccurrencePreOverrideReplacesTheGlobalPre_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A first-occurrence pre override replaces the global pre-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 157
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "preOverrideMs"});
                table39.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "100"});
                table39.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            ""});
#line 158
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table39, "Given ");
#line hidden
#line 162
    await testRunner.WhenAsync("the processor predicts objects at -0.05 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 163
    await testRunner.ThenAsync("the predicted tracks are 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A segment is not covered before its first-occurrence pre override")]
        public async global::System.Threading.Tasks.Task ASegmentIsNotCoveredBeforeItsFirst_OccurrencePreOverride()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A segment is not covered before its first-occurrence pre override", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 165
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "preOverrideMs"});
                table40.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "100"});
                table40.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            ""});
#line 166
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table40, "Given ");
#line hidden
#line 170
    await testRunner.WhenAsync("the processor predicts objects at -0.20 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 171
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A last-occurrence post override replaces the global post-buffer")]
        public async global::System.Threading.Tasks.Task ALast_OccurrencePostOverrideReplacesTheGlobalPost_Buffer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A last-occurrence post override replaces the global post-buffer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 173
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "postOverrideMs"});
                table41.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            ""});
                table41.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "400"});
#line 174
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table41, "Given ");
#line hidden
#line 178
    await testRunner.WhenAsync("the processor predicts objects at 1.3 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
    await testRunner.ThenAsync("the predicted tracks are 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A segment is not covered after its last-occurrence post override")]
        public async global::System.Threading.Tasks.Task ASegmentIsNotCoveredAfterItsLast_OccurrencePostOverride()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A segment is not covered after its last-occurrence post override", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 181
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "postOverrideMs"});
                table42.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            ""});
                table42.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "400"});
#line 182
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table42, "Given ");
#line hidden
#line 186
    await testRunner.WhenAsync("the processor predicts objects at 1.5 seconds with a 0.25 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 187
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Interpolation stops at a missing analyzed frame")]
        public async global::System.Threading.Tasks.Task InterpolationStopsAtAMissingAnalyzedFrame()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interpolation stops at a missing analyzed frame", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 189
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table43 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "frameIndex"});
                table43.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "0"});
                table43.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "1"});
                table43.AddRow(new string[] {
                            "3.0",
                            "7",
                            "200",
                            "3"});
#line 190
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table43, "Given ");
#line hidden
#line 195
    await testRunner.WhenAsync("the processor predicts objects at 2.0 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 196
    await testRunner.ThenAsync("no predicted objects are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Interpolated boxes copy override metadata and blur shape")]
        public async global::System.Threading.Tasks.Task InterpolatedBoxesCopyOverrideMetadataAndBlurShape()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interpolated boxes copy override metadata and blur shape", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 198
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table44 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "blurShape",
                            "blurSizePercentOverride",
                            "preOverrideMs",
                            "postOverrideMs"});
                table44.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "rectangle",
                            "150",
                            "100",
                            ""});
                table44.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "rectangle",
                            "150",
                            "",
                            "400"});
#line 199
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table44, "Given ");
#line hidden
#line 203
    await testRunner.WhenAsync("the processor predicts objects at 0.5 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table45 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x",
                            "blurShape",
                            "blurSizePercentOverride",
                            "postOverrideMs"});
                table45.AddRow(new string[] {
                            "7",
                            "55",
                            "rectangle",
                            "150",
                            "400"});
#line 204
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table45, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Interpolated boxes copy occurrence blur and track time buffer metadata")]
        public async global::System.Threading.Tasks.Task InterpolatedBoxesCopyOccurrenceBlurAndTrackTimeBufferMetadata()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Interpolated boxes copy occurrence blur and track time buffer metadata", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 208
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table46 = new global::Reqnroll.Table(new string[] {
                            "timeSeconds",
                            "trackId",
                            "x",
                            "occurrenceBlurSizePercentOverride",
                            "trackTimeBufferMsOverride"});
                table46.AddRow(new string[] {
                            "0.0",
                            "7",
                            "10",
                            "180",
                            "600"});
                table46.AddRow(new string[] {
                            "1.0",
                            "7",
                            "100",
                            "",
                            "600"});
#line 209
    await testRunner.GivenAsync("analyzed detections for prediction", ((string)(null)), table46, "Given ");
#line hidden
#line 213
    await testRunner.WhenAsync("the processor predicts objects at 0.4 seconds with a 0.0 second buffer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table47 = new global::Reqnroll.Table(new string[] {
                            "trackId",
                            "x",
                            "occurrenceBlurSizePercentOverride",
                            "trackTimeBufferMsOverride"});
                table47.AddRow(new string[] {
                            "7",
                            "46",
                            "180",
                            "600"});
#line 214
    await testRunner.ThenAsync("the predicted objects are", ((string)(null)), table47, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
