// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoAnonymizer.Database;

#nullable disable

namespace VideoAnonymizer.Database.SQLite.Migrations
{
    [DbContext(typeof(VideoAnonymizerDbContext))]
    partial class VideoAnonymizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("AnalyzedFrames");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.DetectedObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalyzedFrameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnalyzedFrameId");

                    b.ToTable("DetectedObjects");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnonomizedPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("BlurSizePercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeBufferMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.HasOne("VideoAnonymizer.Database.Video", "Video")
                        .WithMany("AnalyzedFrames")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.DetectedObject", b =>
                {
                    b.HasOne("VideoAnonymizer.Database.AnalyzedFrame", "AnalyzedFrame")
                        .WithMany("DetectedObjects")
                        .HasForeignKey("AnalyzedFrameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalyzedFrame");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.AnalyzedFrame", b =>
                {
                    b.Navigation("DetectedObjects");
                });

            modelBuilder.Entity("VideoAnonymizer.Database.Video", b =>
                {
                    b.Navigation("AnalyzedFrames");
                });
#pragma warning restore 612, 618
        }
    }
}
